#!/usr/bin/env python3
"""
scripts/test_price_alert_e2e.py
===============================
E2E test for BUY-3130: price alert flow.

Steps:
  1. Provision (or reuse) a QA test API key
  2. Set up a test product in DB (reuse if exists)
  3. Create price alert via PriceAlert model insert
  4. Simulate price drop in DB (update product price below alert threshold)
  5. Call check_and_trigger_price_alerts()
  6. Assert alert.triggered_at is set and PriceAlertDelivery row exists

Run:
    python scripts/test_price_alert_e2e.py

Requires BUYWHERE_DATABASE_URL (falls back to Docker catalog DB).
"""

import asyncio
import os
import sys
import uuid
from decimal import Decimal
from typing import Optional

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from sqlalchemy import select, update, text, func
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import AsyncSessionLocal, get_db
from app.models.product import ApiKey, Product
from app.models.price_alert import PriceAlert
from app.auth import provision_api_key, hash_key
from app.services.price_alert import check_and_trigger_price_alerts


TEST_DEVELOPER_ID = "qa-e2e-price-alert"
TEST_KEY_NAME = "buy3130-e2e"
TEST_PRODUCT_SOURCE = "buywhere-test"
TEST_PRODUCT_MERCHANT = "buywhere-test-merchant"
INITIAL_PRICE = Decimal("100.00")
DROPPED_PRICE = Decimal("75.00")
TARGET_PRICE = Decimal("90.00")


async def get_or_create_test_product(db: AsyncSession) -> Product:
    result = await db.execute(
        select(Product).where(
            Product.source == TEST_PRODUCT_SOURCE,
            Product.merchant_id == TEST_PRODUCT_MERCHANT,
            Product.is_active.is_(True),
        ).limit(1)
    )
    product = result.scalar_one_or_none()
    if product:
        print(f"  Reusing existing test product id={product.id}")
        return product

    result = await db.execute(
        select(Product.id).order_by(Product.id.desc()).limit(1)
    )
    last_id = result.scalar()
    next_id = (last_id + 1) if last_id else 1

    product = Product(
        id=next_id,
        sku=f"qa-e2e-{uuid.uuid4().hex[:8]}",
        source=TEST_PRODUCT_SOURCE,
        merchant_id=TEST_PRODUCT_MERCHANT,
        title="E2E Test Product — Price Alert QA",
        description="Auto-generated by BUY-3130 E2E test. Safe to delete.",
        price=INITIAL_PRICE,
        currency="SGD",
        price_sgd=INITIAL_PRICE,
        region="sg",
        country_code="SG",
        url="https://buywhere.ai/e2e-test",
        brand="BuyWhere QA",
        category="Test",
        is_active=True,
        is_available=True,
        in_stock=True,
    )
    db.add(product)
    await db.flush()
    await db.refresh(product)
    print(f"  Created test product id={product.id}")
    return product


async def get_or_create_test_api_key(db: AsyncSession) -> tuple[str, ApiKey]:
    result = await db.execute(
        select(ApiKey).where(
            ApiKey.developer_id == TEST_DEVELOPER_ID,
            ApiKey.name == TEST_KEY_NAME,
            ApiKey.is_active.is_(True),
        )
    )
    api_key = result.scalar_one_or_none()
    if api_key:
        result2 = await db.execute(
            select(ApiKey).where(ApiKey.id == api_key.id)
        )
        key_row = result2.first()
        raw_key = f"bw_test_{uuid.uuid4().hex}{uuid.uuid4().hex[:8]}"
        key_hash = hash_key(raw_key)
        await db.execute(
            update(ApiKey)
            .where(ApiKey.id == api_key.id)
            .values(key_hash=key_hash)
        )
        await db.commit()
        print(f"  Reusing and rotating test API key id={api_key.id}")
        return raw_key, api_key

    raw_key, api_key = await provision_api_key(
        developer_id=TEST_DEVELOPER_ID,
        name=TEST_KEY_NAME,
        tier="basic",
        db=db,
        rate_limit=1000,
    )
    print(f"  Provisioned new test API key id={api_key.id}")
    return raw_key, api_key


async def cleanup_test_alerts(db: AsyncSession, product_id: int, developer_id: str):
    await db.execute(
        update(PriceAlert)
        .where(
            PriceAlert.product_id == product_id,
            PriceAlert.developer_id == developer_id,
        )
        .values(is_active=False, updated_at=func.now())
    )
    await db.flush()


async def run_test() -> bool:
    print("\n=== BUY-3130 E2E: Price Alert Flow ===\n")

    async with AsyncSessionLocal() as db:
        raw_key, api_key = await get_or_create_test_api_key(db)
        product = await get_or_create_test_product(db)
        product_id = product.id

        await cleanup_test_alerts(db, product_id, TEST_DEVELOPER_ID)

        print(f"  Creating price alert: product_id={product_id}, "
              f"target={TARGET_PRICE} SGD, direction=below")

        alert_id = str(uuid.uuid4())
        alert = PriceAlert(
            id=alert_id,
            developer_id=TEST_DEVELOPER_ID,
            product_id=product_id,
            target_price=TARGET_PRICE,
            direction="below",
            currency="SGD",
            callback_url="https://buywhere.ai/e2e-test-webhook",
            is_active=True,
        )
        db.add(alert)
        await db.flush()
        await db.refresh(alert)
        print(f"  Alert created id={alert.id}, is_active={alert.is_active}")

        print(f"  Simulating price drop: {INITIAL_PRICE} -> {DROPPED_PRICE}")
        await db.execute(
            update(Product)
            .where(Product.id == product_id)
            .values(
                price=DROPPED_PRICE,
                price_sgd=DROPPED_PRICE,
            )
        )
        await db.flush()

        print(f"  Calling check_and_trigger_price_alerts(db, {product_id}, "
              f"{DROPPED_PRICE}, 'SGD')")

        try:
            triggered = await check_and_trigger_price_alerts(
                db,
                str(product_id),
                Decimal(str(DROPPED_PRICE)),
                "SGD",
            )
            print(f"  check_and_trigger_price_alerts returned: {triggered}")
        except Exception as e:
            print(f"  FAIL: check_and_trigger_price_alerts raised {type(e).__name__}: {e}")
            return False

        await db.flush()

        result = await db.execute(
            select(PriceAlert).where(PriceAlert.id == alert_id)
        )
        triggered_alert = result.scalar_one_or_none()

        if not triggered_alert:
            print("  FAIL: Alert record not found after trigger")
            return False

        print(f"  Alert state after trigger: is_active={triggered_alert.is_active}, "
              f"triggered_at={triggered_alert.triggered_at}")

        if triggered_alert.triggered_at is None:
            print("  FAIL: alert.triggered_at is still NULL — alert was not marked triggered")
            return False

        from app.models.price_alert import PriceAlertDelivery
        delivery_result = await db.execute(
            select(PriceAlertDelivery).where(
                PriceAlertDelivery.alert_id == alert_id
            )
        )
        delivery = delivery_result.scalar_one_or_none()

        if delivery is None:
            print("  FAIL: PriceAlertDelivery record not found — notification not queued")
            return False

        print(f"  PriceAlertDelivery found: id={delivery.id}, event_type={delivery.event_type}, "
              f"attempts={delivery.attempts}")

        if delivery.event_type != "price_triggered":
            print(f"  FAIL: unexpected event_type={delivery.event_type}, expected='price_triggered'")
            return False

        if delivery.payload is None:
            print("  FAIL: PriceAlertDelivery.payload is NULL")
            return False

        print("\n=== TEST PASSED ===")
        return True


def main():
    success = asyncio.run(run_test())
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
